[tool.poetry]
name = "swapmaster"
version = "0.1.0"
description = ""
authors = ["Mikky07 <mesarevartem9@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
