"""Added order payment status

Revision ID: 03449887807c
Revises: 0c2d43501730
Create Date: 2024-03-07 21:44:42.754189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03449887807c'
down_revision: Union[str, None] = '0c2d43501730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    payment_status = postgresql.ENUM('PAID', 'UNPAID', name='orderpaymentstatusenum')
    payment_status.create(op.get_bind())
    op.add_column('orders', sa.Column('payment_status', payment_status, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_status')
    op.execute("drop type orderpaymentstatusenum")
    # ### end Alembic commands ###
