"""Added reception wallet to pair

Revision ID: 0c2d43501730
Revises: 57d1da8b74f5
Create Date: 2024-03-04 18:09:14.068073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2d43501730'
down_revision: Union[str, None] = '57d1da8b74f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_pair_id_pairs', 'orders', type_='foreignkey')
    op.drop_constraint('fk_orders_user_id_users', 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_user_id_users'), 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_orders_pair_id_pairs'), 'orders', 'pairs', ['pair_id'], ['id'], ondelete='CASCADE')
    op.add_column('pairs', sa.Column('reception_wallet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_pairs_reception_wallet_id_wallets'), 'pairs', 'wallets', ['reception_wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_pairs_reception_wallet_id_wallets'), 'pairs', type_='foreignkey')
    op.drop_column('pairs', 'reception_wallet_id')
    op.drop_constraint(op.f('fk_orders_pair_id_pairs'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('fk_orders_user_id_users'), 'orders', type_='foreignkey')
    op.create_foreign_key('fk_orders_user_id_users', 'orders', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_orders_pair_id_pairs', 'orders', 'pairs', ['pair_id'], ['id'])
    # ### end Alembic commands ###
