"""Added requisits

Revision ID: 386ccefb62ad
Revises: 4f0fde8783fa
Create Date: 2024-02-16 22:37:40.806645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386ccefb62ad'
down_revision: Union[str, None] = '4f0fde8783fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requisites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=True),
    sa.Column('regular_expression', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pair_id'], ['pairs.id'], name=op.f('fk_requisites_pair_id_pairs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requisites')),
    sa.UniqueConstraint('name', name=op.f('uq_requisites_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requisites')
    # ### end Alembic commands ###
