"""Added order_requisite table

Revision ID: 40e9324ac318
Revises: 386ccefb62ad
Create Date: 2024-02-20 12:06:50.153328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e9324ac318'
down_revision: Union[str, None] = '386ccefb62ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_requisite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('requisite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_requisite_order_id_orders')),
    sa.ForeignKeyConstraint(['requisite_id'], ['requisites.id'], name=op.f('fk_order_requisite_requisite_id_requisites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_requisite'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_requisite')
    # ### end Alembic commands ###
