"""Added wallets table

Revision ID: 46323b046607
Revises: ed884e4566f6
Create Date: 2024-02-12 18:19:09.973618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46323b046607'
down_revision: Union[str, None] = 'ed884e4566f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets')),
    sa.UniqueConstraint('name', name=op.f('uq_wallets_name'))
    )
    op.add_column('methods', sa.Column('reserve_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_methods_reserve_id_reserves'), 'methods', 'reserves', ['reserve_id'], ['id'])
    op.add_column('reserves', sa.Column('wallet_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_reserves_method_id_methods', 'reserves', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reserves_wallet_id_wallets'), 'reserves', 'wallets', ['wallet_id'], ['id'])
    op.drop_column('reserves', 'method_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserves', sa.Column('method_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_reserves_wallet_id_wallets'), 'reserves', type_='foreignkey')
    op.create_foreign_key('fk_reserves_method_id_methods', 'reserves', 'methods', ['method_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reserves', 'wallet_id')
    op.drop_constraint(op.f('fk_methods_reserve_id_reserves'), 'methods', type_='foreignkey')
    op.drop_column('methods', 'reserve_id')
    op.drop_table('wallets')
    # ### end Alembic commands ###
