"""Added users verification status field

Revision ID: 57d1da8b74f5
Revises: 998669c75eaa
Create Date: 2024-02-25 15:47:05.418522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57d1da8b74f5'
down_revision: Union[str, None] = '998669c75eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    verification_status = postgresql.ENUM('UNVERIFIED', 'VERIFIED', name='verificationstatusenum')
    verification_status.create(op.get_bind())
    op.add_column('users', sa.Column('verification_status', verification_status, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_status')
    op.execute("drop type verificationstatusenum")
    # ### end Alembic commands ###
