"""Added orders table

Revision ID: 68e7b658fbfb
Revises: f343d20bd071
Create Date: 2024-02-04 13:39:09.632123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68e7b658fbfb'
down_revision: Union[str, None] = 'f343d20bd071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('to_receive', sa.Float(), nullable=False),
    sa.Column('to_send', sa.Float(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_finish', sa.DateTime(), nullable=True),
    sa.Column(
        'status',
        postgresql.ENUM('PROCESSING', 'FINISHED', 'CANCELED', name='orderstatusenum'),
        nullable=False,
        server_default='PROCESSING'
    ),
    sa.ForeignKeyConstraint(['pair_id'], ['pairs.id'], name=op.f('fk_orders_pair_id_pairs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.execute("DROP TYPE orderstatusenum")
    # ### end Alembic commands ###
