"""Added update method column to courses

Revision ID: 7f83f906139e
Revises: 40e9324ac318
Create Date: 2024-02-20 18:59:47.534034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f83f906139e'
down_revision: Union[str, None] = '40e9324ac318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    update_method = postgresql.ENUM('LOCAL', 'REMOTE', name='courseupdatemethodenum', nullable=False)
    update_method.create(op.get_bind())
    op.add_column('courses', sa.Column('update_method', update_method))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'update_method')
    op.execute('drop type courseupdatemethodenum')
    # ### end Alembic commands ###
