"""Refactored relationship with method and reserve

Revision ID: aaba2a4a7ea7
Revises: bcc40ae7b947
Create Date: 2024-02-23 20:58:39.024825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaba2a4a7ea7'
down_revision: Union[str, None] = 'bcc40ae7b947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reserves', 'method_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('fk_reserves_method_id_methods', 'reserves', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_reserves_method_id_methods', 'reserves', 'methods', ['method_id'], ['id'])
    op.alter_column('reserves', 'method_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
