"""Added courses table

Revision ID: ad4a0d8e1581
Revises: 68e7b658fbfb
Create Date: 2024-02-05 14:46:37.702481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad4a0d8e1581'
down_revision: Union[str, None] = '68e7b658fbfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pair_id'], ['pairs.id'], name=op.f('fk_courses_pair_id_pairs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )

    course_obtaining_method = postgresql.ENUM('STATIC', 'STOCK_EXCHANGE_SERVICE', name='courseobtainingmethod')
    course_obtaining_method.create(op.get_bind())

    op.add_column('pairs', sa.Column(
        'course_obtaining_method',
        course_obtaining_method,
        nullable=False,
        server_default='STATIC'
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pairs', 'course_obtaining_method')

    course_obtaining_method = postgresql.ENUM('STATIC', 'STOCK_EXCHANGE_SERVICE', name='courseobtainingmethod')
    course_obtaining_method.create(op.get_bind())

    op.drop_table('courses')
    # ### end Alembic commands ###
